### ISSUE TITLE
Issue with tippy position

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#575]
![Explore the Anime Universe_ Your Gateway to Otaku Delights! — Firefox Nightly 8_14_2023 10_12_47 PM](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/e5332a85-99aa-41e7-80a0-06cc071fbc25)

**Comment by tokitou-san** [comment]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/b959c3674f2164aeda219cd0b109240024ddf2cf/src/routes/explore/%2Bpage.svelte#L280-L281
LOL No, I set this position for a reason.
Since it was `interactive` we cant hover or see the next card... and positioning tippy on top and bottom is not a good option.
But feel free to change.
